import type { OgonlineAgencyDef } from '../generic/ogonline.js';

/*
 * Estate agents in the Randstad whose OGonline website serves
 * /nl/realtime-listings/consumer. Every entry answered that URL with a JSON
 * list on 2026-09-24 (one request each) and rents homes in the listed
 * municipalities, taken from the cities of its rentals in that list. The
 * contact mode comes from one listing page per agency, read the same day:
 * `form` where the listing page has the shared OGonline reply form without a
 * captcha, `email` where the form has a captcha the agent must not solve or
 * no reply form was seen.
 *
 * Checked the same day and left out: csvmakelaars.nl, elnovi.nl,
 * robertvanderzwan.nl, vangroenigen.nl and 070vastgoed.nl (no rentals in the
 * list), cdmakelaardij.nl and vrielingmakelaars.nl (one or two rentals, none
 * since 2024), maisonmanagement.nl (only listings from 2020),
 * kampenkoolhof.nl and jelleooteman.nl (rentals outside the Randstad), and a
 * dozen agencies whose site is not built on OGonline.
 */
export const OGONLINE_AGENCIES: OgonlineAgencyDef[] = [
  {
    id: 'verra',
    name: 'Verra Makelaars',
    homepage: 'https://www.verra.nl',
    regions: [
      'den haag',
      'rotterdam',
      'delft',
      'leiden',
      'rijswijk',
      'leidschendam-voorburg',
      'wassenaar',
      'voorschoten',
      'oegstgeest',
      'noordwijk',
      'albrandswaard',
      'barendrecht',
      'capelle aan den ijssel',
      'nissewaard',
      'lansingerland',
      'maassluis',
      'utrecht',
    ],
    contact: 'form',
    note: 'the largest OGonline rental offer in the research (655 rentals); each office has its own form address',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'van-daal',
    name: 'Van Daal Makelaardij',
    homepage: 'https://www.vandaalmakelaardij.nl',
    regions: ['delft', 'rijswijk', 'den haag', 'midden-delfland', 'zoeterwoude', 'rotterdam'],
    contact: 'email',
    email: 'info@vandaalmakelaardij.nl',
    note: 'no rental listing page was online to read the form from',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'van-paaschen',
    name: 'Van Paaschen Makelaardij',
    homepage: 'https://www.vanpaaschen.nl',
    regions: ['den haag', 'leidschendam-voorburg', 'rijswijk', 'wassenaar'],
    contact: 'form',
    email: 'info@vanpaaschen.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'atrium',
    name: 'Atrium Makelaars',
    homepage: 'https://www.atrium-makelaars.nl',
    regions: ['den haag', 'rijswijk', 'leidschendam-voorburg', 'rotterdam', 'teylingen'],
    contact: 'email',
    email: 'info@atrium-makelaars.nl',
    note: 'the reply form asks a sum question (a captcha)',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'lex-van-leeuwen',
    name: 'Lex van Leeuwen Makelaars',
    homepage: 'https://www.lexvanleeuwen.nl',
    regions: ['den haag'],
    contact: 'form',
    email: 'info@lexvanleeuwen.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'dekkers-de-groot',
    name: 'Dekkers de Groot Makelaardij',
    homepage: 'https://www.dekkersdegroot.nl',
    regions: ['den haag'],
    contact: 'email',
    email: 'info@dekkersdegroot.nl',
    note: 'the reply form asks a sum question (a captcha)',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'estata',
    name: 'Estata Makelaars',
    homepage: 'https://www.estata.nl',
    regions: ['den haag', 'wassenaar', 'rijswijk', 'leidschendam-voorburg', 'westland', 'zoetermeer'],
    contact: 'form',
    email: 'info@estata.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'amsterdam-housing',
    name: 'Amsterdam Housing',
    homepage: 'https://www.amsterdamhousing.com',
    regions: ['amsterdam', 'amstelveen', 'uithoorn', 'haarlemmermeer', 'de ronde venen', 'aalsmeer', 'purmerend'],
    contact: 'form',
    email: 'info@amsterdamhousing.com',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'bjornd',
    name: 'Bjornd Makelaardij',
    homepage: 'https://www.bjornd.nl',
    regions: ['delft', 'pijnacker-nootdorp', 'midden-delfland', 'rijswijk'],
    contact: 'form',
    email: 'info@bjornd.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'the-house-of-expats',
    name: 'The House of Expats',
    homepage: 'https://www.thehouseofexpats.com',
    regions: ['den haag', 'westland'],
    contact: 'form',
    email: 'info@thehouseofexpats.com',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'bns-rental-service',
    name: 'B&S Rental Service',
    homepage: 'https://www.bnsrentalservice.nl',
    regions: ['utrecht', 'nieuwegein', 'houten'],
    contact: 'email',
    email: 'info@bnsrentalservice.nl',
    note: 'the reply form has a reCAPTCHA checkbox',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'perfect-rent',
    name: 'Perfect Rent',
    homepage: 'https://www.perfectrent.nl',
    regions: ['rotterdam'],
    contact: 'form',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'residence',
    name: 'Residence Makelaars',
    homepage: 'https://www.residencemakelaars.com',
    regions: ['den haag', 'leidschendam-voorburg', 'wassenaar', 'rijswijk'],
    contact: 'form',
    email: 'info@residencemakelaars.com',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'keij-stefels',
    name: 'Keij & Stefels',
    homepage: 'https://www.keij-stefels.nl',
    regions: ['amsterdam', 'amstelveen', 'diemen', 'ouder-amstel', 'almere', 'utrecht'],
    contact: 'form',
    email: 'info@keij-stefels.nl',
    intervalSec: 600, // a 2 MB list with few rentals on offer at a time
    verifiedAt: '2026-09-24',
  },
  {
    id: 'lankhuijzen',
    name: 'Lankhuijzen Makelaars',
    homepage: 'https://www.lankhuijzen.nl',
    regions: ['rotterdam', 'schiedam', 'barendrecht'],
    contact: 'form',
    email: 'info@lankhuijzen.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'expat-real-estate',
    name: 'Expat & Real Estate',
    homepage: 'https://www.expat-realestate.nl',
    regions: ['den haag', 'leidschendam-voorburg', 'delft', 'rijswijk', 'pijnacker-nootdorp', 'wassenaar', 'voorschoten', 'westland'],
    contact: 'form',
    email: 'info@expat-realestate.nl',
    intervalSec: 600, // a 3 MB list
    verifiedAt: '2026-09-24',
  },
  {
    id: 'deerenberg',
    name: 'Deerenberg & Van Leeuwen Makelaars',
    homepage: 'https://www.deerenberg.nl',
    regions: ['alphen aan den rijn', 'nieuwkoop'],
    contact: 'email',
    email: 'makelaardij@deerenberg.nl',
    note: 'no rental reply form was seen, only a bidding form',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'expat-property-management',
    name: 'Expat & Property Management',
    homepage: 'https://www.expatpropertymanagement.nl',
    regions: ['den haag', 'rijswijk', 'leiden', 'zoetermeer', 'westland'],
    contact: 'form',
    email: 'info@ep-m.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'nelisse',
    name: 'Nelisse Makelaarsgroep',
    homepage: 'https://www.nelisse.nl',
    regions: ['den haag', 'rijswijk'],
    contact: 'form',
    email: 'info@nelisse.nl',
    intervalSec: 900, // a 2 MB list, mostly sales
    verifiedAt: '2026-09-24',
  },
  {
    id: 'van-den-brink',
    name: 'Carla van den Brink Makelaars',
    homepage: 'https://www.vandenbrink.nl',
    regions: ['amsterdam', 'amstelveen'],
    contact: 'form',
    email: 'info@vandenbrink.nl',
    verifiedAt: '2026-09-24',
  },
  {
    id: 'wvo',
    name: 'WVO Makelaarsgroep',
    homepage: 'https://www.wvo.nl',
    regions: ['utrecht', 'nieuwegein', 'zeist', 'de bilt', 'hilversum'],
    contact: 'form',
    email: 'utrecht@wvo.nl',
    verifiedAt: '2026-09-24',
  },
];
